package com.vacanza.backend.integration.ai;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vacanza.backend.dto.weather.DailyWeatherSummary;
import com.vacanza.backend.dto.weather.DayPartWeatherDay;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * DTOs for AI chat service proxy requests/responses.
 * AI service returns snake_case JSON.
 */
public final class AiChatDto {

    private AiChatDto() {}

    /** Request body for sending a message. */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class MessageSendRequest {
        private String content;
    }

    /** Response when creating a conversation. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ConversationCreateResponse {
        private UUID id;
    }

    /** Conversation item in list response. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ConversationListItem {
        private UUID id;
        @JsonProperty("created_at")
        private Instant createdAt;
        @JsonProperty("updated_at")
        private Instant updatedAt;
        @JsonProperty("user_id")
        private UUID userId;
        private String title;
    }

    /** Single message in history. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class MessageItem {
        private UUID id;
        private String role;
        private String content;
        @JsonProperty("created_at")
        private Instant createdAt;
    }

    /** AI response when sending a message. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class MessageSendResponse {
        private String content;

        @JsonProperty("extracted_preferences")
        private List<ExtractedPreference> extractedPreferences;

        @JsonProperty("route_data")
        private RouteData routeData;

        /** Short contextual message about the route (e.g. "Müzeleri sevdiğini biliyordum, o yüzden rotanda ağırlıklı olarak müzeler var."). */
        @JsonProperty("route_summary_message")
        private String routeSummaryMessage;

        /**
         * Persisted {@code ai_routes.route_id} after this turn saved route JSON (Java-only).
         */
        @JsonProperty("route_id")
        private UUID routeId;

        /**
         * Set by Java when the response is tied to a known conversation (e.g. map polygon route flow).
         * Not returned by the Python AI service for normal chat sends.
         */
        @JsonProperty("conversation_id")
        private UUID conversationId;
    }

    /** A single stop/place in a day's route plan. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RouteWaypoint {
        private String name;
        private String description;
        private String category;
        private int day;
        private int order;
        private Double latitude;
        private Double longitude;

        @JsonProperty("estimated_duration_min")
        private Integer estimatedDurationMin;

        @JsonProperty("time_slot")
        private String timeSlot;

        /** Minutes walking from previous stop; null for the first stop of the day. */
        @JsonProperty("travel_from_previous_min")
        private Integer travelFromPreviousMin;

        @JsonProperty("arrival_time_local")
        private String arrivalTimeLocal;

        @JsonProperty("departure_time_local")
        private String departureTimeLocal;
    }

    /** One day's itinerary within a multi-day route. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class DayPlan {
        private int day;
        private String title;
        private List<RouteWaypoint> waypoints;

        @JsonProperty("day_start_local")
        private String dayStartLocal;

        @JsonProperty("day_end_local")
        private String dayEndLocal;
    }

    /** Complete multi-day travel route generated by AI. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RouteData {
        private String title;
        private String destination;

        @JsonProperty("total_days")
        private int totalDays;

        private List<DayPlan> days;
        private String notes;

        /** Open-Meteo daily summaries; set by backend after POI+weather flow. */
        @JsonProperty("weather_forecast")
        private List<DailyWeatherSummary> weatherForecast;

        /** Morning/afternoon/evening slots from hourly forecast; set by backend with POI+weather flow. */
        @JsonProperty("weather_day_parts")
        private List<DayPartWeatherDay> weatherDayParts;
    }

    /** A single preference extracted by AI from the conversation. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ExtractedPreference {
        @JsonProperty("preference_key")
        private String preferenceKey;

        @JsonProperty("preference_value")
        private String preferenceValue;

        private Double confidence;
    }

    /** Request body for POST /events/rank — rank Ticketmaster events against a saved route. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class EventRankingRequest {
        private String destination;

        @JsonProperty("total_days")
        private int totalDays;

        @JsonProperty("route_days")
        private List<RouteDaySummaryForAi> routeDays;

        private List<EventBriefForRanking> events;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RouteDaySummaryForAi {
        private int day;
        private String title;

        @JsonProperty("waypoint_categories")
        private List<String> waypointCategories;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class EventBriefForRanking {
        private String id;
        private String name;
        private String description;
        private String startTime;
        private String category;
        private String venueName;
    }

    /** Response from POST /events/rank. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class EventRankingAiResponse {
        private String message;

        @JsonProperty("ranked_events")
        private List<EventRankingItem> rankedEvents;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class EventRankingItem {
        private String id;

        @JsonProperty("matched_day")
        private Integer matchedDay;

        @JsonProperty("match_reason")
        private String matchReason;

        @JsonProperty("relevance_score")
        private Double relevanceScore;
    }
}
