package com.vacanza.backend.integration.ai;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * DTOs for AI chat service proxy requests/responses.
 * AI service returns snake_case JSON.
 */
public final class AiChatDto {

    private AiChatDto() {}

    /** Request body for sending a message. */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class MessageSendRequest {
        private String content;
    }

    /** Response when creating a conversation. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ConversationCreateResponse {
        private UUID id;
    }

    /** Conversation item in list response. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ConversationListItem {
        private UUID id;
        @JsonProperty("created_at")
        private Instant createdAt;
        @JsonProperty("updated_at")
        private Instant updatedAt;
        @JsonProperty("user_id")
        private UUID userId;
        private String title;
    }

    /** Single message in history. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class MessageItem {
        private UUID id;
        private String role;
        private String content;
        @JsonProperty("created_at")
        private Instant createdAt;
    }

    /** AI response when sending a message. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class MessageSendResponse {
        private String content;

        @JsonProperty("extracted_preferences")
        private List<ExtractedPreference> extractedPreferences;

        @JsonProperty("route_data")
        private RouteData routeData;

        /** Short contextual message about the route (e.g. "Müzeleri sevdiğini biliyordum, o yüzden rotanda ağırlıklı olarak müzeler var."). */
        @JsonProperty("route_summary_message")
        private String routeSummaryMessage;
    }

    /** A single stop/place in a day's route plan. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RouteWaypoint {
        private String name;
        private String description;
        private String category;
        private int day;
        private int order;
        private Double latitude;
        private Double longitude;

        @JsonProperty("estimated_duration_min")
        private Integer estimatedDurationMin;

        @JsonProperty("time_slot")
        private String timeSlot;
    }

    /** One day's itinerary within a multi-day route. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class DayPlan {
        private int day;
        private String title;
        private List<RouteWaypoint> waypoints;
    }

    /** Complete multi-day travel route generated by AI. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RouteData {
        private String title;
        private String destination;

        @JsonProperty("total_days")
        private int totalDays;

        private List<DayPlan> days;
        private String notes;
    }

    /** A single preference extracted by AI from the conversation. */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ExtractedPreference {
        @JsonProperty("preference_key")
        private String preferenceKey;

        @JsonProperty("preference_value")
        private String preferenceValue;

        private Double confidence;
    }
}
