"""Chat API schemas."""

from datetime import datetime
from uuid import UUID

from pydantic import AliasChoices, BaseModel, ConfigDict, Field

from app.schemas.preference_extraction import ExtractedPreference


class UserProfileForAi(BaseModel):
    """User profile for AI (X-User-Profile). Mirrors Java UserProfileForAi (identity + UserPreferences).

    Budget: backend always sends ``dailyBudget`` (camelCase). We also accept legacy JSON key ``budget``;
    both map to ``dailyBudget`` on this model.
    """

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    # Identity (UserInfo)
    displayName: str | None = None
    firstName: str | None = None
    middleName: str | None = None
    lastName: str | None = None
    preferredName: str | None = None
    country: str | None = None
    birthDate: str | None = None
    gender: str | None = None
    profileImageUrl: str | None = None
    joinDate: str | None = None

    # Travel style & interests
    travelStyle: str | None = None
    favoriteCategories: list[str] | None = None
    activityLevel: str | None = None
    cuisinePreferences: list[str] | None = None

    # Trip preferences
    preferredClimate: str | None = None
    tripPace: str | None = None
    accommodationType: str | None = None
    transportPreference: str | None = None

    # Constraints & accessibility
    dietaryRestrictions: list[str] | None = None
    accessibilityNeeds: list[str] | None = None
    avoidCategories: list[str] | None = None

    # Budget — Java / X-User-Profile uses dailyBudget; "budget" accepted for older payloads
    dailyBudget: str | None = Field(
        default=None,
        validation_alias=AliasChoices("dailyBudget", "budget"),
        description="Daily budget amount (string); backend field name is dailyBudget.",
    )
    budgetCurrency: str | None = None
    splurgeCategories: list[str] | None = None

    # Language
    preferredLanguage: str | None = None
    spokenLanguages: list[str] | None = None

    # Favorited / saved POIs (injected by Java backend from user_interactions table)
    savedPoiNames: list[str] | None = None


class ConversationCreateResponse(BaseModel):
    """Response when creating a new conversation."""

    id: UUID


class ConversationListItem(BaseModel):
    """Conversation in list response."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    created_at: datetime
    updated_at: datetime
    user_id: UUID | None
    title: str | None = None


class MessageSend(BaseModel):
    """Request body for sending a message."""

    content: str


class MessageItem(BaseModel):
    """Single message in history/response."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    role: str
    content: str
    created_at: datetime


class RouteWaypoint(BaseModel):
    """A single stop/place in a day's route plan."""

    name: str
    description: str | None = None
    category: str | None = None
    day: int
    order: int
    latitude: float | None = None
    longitude: float | None = None
    estimated_duration_min: int | None = None
    time_slot: str | None = None
    # Filled by Java backend after generation (Mapbox walking + dwell times)
    travel_from_previous_min: int | None = None
    arrival_time_local: str | None = None
    departure_time_local: str | None = None
    # Set by adaptive adjustment when stop is known closed/unavailable
    unavailable: bool | None = None


class DayPlan(BaseModel):
    """One day's itinerary within a multi-day route."""

    day: int
    title: str
    waypoints: list[RouteWaypoint] = Field(default_factory=list)
    day_start_local: str | None = None
    day_end_local: str | None = None


class RouteData(BaseModel):
    """Complete multi-day travel route generated by AI."""

    title: str
    destination: str
    total_days: int
    days: list[DayPlan] = Field(default_factory=list)
    notes: str | None = None
    # True = narrow event search to trip dates; false/omit = ~30-day broad search (Java backend)
    trip_dates_user_specified: bool | None = None
    # First day of trip when user stated dates (YYYY-MM-DD); Java prefers this over weather for events
    trip_start_date: str | None = None
    # Filled by Java backend (Open-Meteo); optional in model output
    weather_forecast: list | None = None
    # Morning/afternoon/evening planning hints; optional, set by Java backend
    weather_day_parts: list | None = None


class MessageSendResponse(BaseModel):
    """AI response when sending a message."""

    content: str
    extracted_preferences: list[ExtractedPreference] = Field(default_factory=list)
    route_data: RouteData | None = None
