"""Chat API schemas."""

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from app.schemas.preference_extraction import ExtractedPreference


class UserProfileForAi(BaseModel):
    """User profile for AI personalization (from X-User-Profile header)."""

    displayName: str | None = None
    firstName: str | None = None
    middleName: str | None = None
    lastName: str | None = None
    preferredName: str | None = None
    country: str | None = None
    birthDate: str | None = None
    gender: str | None = None
    budget: str | None = None
    profileImageUrl: str | None = None
    joinDate: str | None = None


class ConversationCreateResponse(BaseModel):
    """Response when creating a new conversation."""

    id: UUID


class ConversationListItem(BaseModel):
    """Conversation in list response."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    created_at: datetime
    updated_at: datetime
    user_id: UUID | None
    title: str | None = None


class MessageSend(BaseModel):
    """Request body for sending a message."""

    content: str


class MessageItem(BaseModel):
    """Single message in history/response."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    role: str
    content: str
    created_at: datetime


class RouteWaypoint(BaseModel):
    """A single stop/place in a day's route plan."""

    name: str
    description: str | None = None
    category: str | None = None
    day: int
    order: int
    latitude: float | None = None
    longitude: float | None = None
    estimated_duration_min: int | None = None
    time_slot: str | None = None


class DayPlan(BaseModel):
    """One day's itinerary within a multi-day route."""

    day: int
    title: str
    waypoints: list[RouteWaypoint] = Field(default_factory=list)


class RouteData(BaseModel):
    """Complete multi-day travel route generated by AI."""

    title: str
    destination: str
    total_days: int
    days: list[DayPlan] = Field(default_factory=list)
    notes: str | None = None


class MessageSendResponse(BaseModel):
    """AI response when sending a message."""

    content: str
    extracted_preferences: list[ExtractedPreference] = Field(default_factory=list)
    route_data: RouteData | None = None
