// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjBpzaQ6X5LdZR-Oxft8eh1Sg4q5OknWE',
    appId: '1:424211182688:web:7e4c7ddeb6c7ed04e3bf05',
    messagingSenderId: '424211182688',
    projectId: 'vacanza-b364c',
    authDomain: 'vacanza-b364c.firebaseapp.com',
    storageBucket: 'vacanza-b364c.firebasestorage.app',
    measurementId: 'G-CRPL3K2FG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfWhcCHwvOsALQHXX0wVtM9dYNj3tdLWs',
    appId: '1:424211182688:android:24bd3bc0399d8de8e3bf05',
    messagingSenderId: '424211182688',
    projectId: 'vacanza-b364c',
    storageBucket: 'vacanza-b364c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6qHfgVz2nGqEqEZIR3u6rA4zkKI_z8sA',
    appId: '1:424211182688:ios:14c85cbcd86f70e5e3bf05',
    messagingSenderId: '424211182688',
    projectId: 'vacanza-b364c',
    storageBucket: 'vacanza-b364c.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6qHfgVz2nGqEqEZIR3u6rA4zkKI_z8sA',
    appId: '1:424211182688:ios:14c85cbcd86f70e5e3bf05',
    messagingSenderId: '424211182688',
    projectId: 'vacanza-b364c',
    storageBucket: 'vacanza-b364c.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjBpzaQ6X5LdZR-Oxft8eh1Sg4q5OknWE',
    appId: '1:424211182688:web:3a9bdd48549ae935e3bf05',
    messagingSenderId: '424211182688',
    projectId: 'vacanza-b364c',
    authDomain: 'vacanza-b364c.firebaseapp.com',
    storageBucket: 'vacanza-b364c.firebasestorage.app',
    measurementId: 'G-Q0959Y3NSM',
  );
}